dataset: ImageNet
# choices=[
#     'aircraft', 'car', 'flowers102',
#     'food101', 'cub200', 'pets',
#     'cifar10', 'cifar100', 'ImageNet',])
train_batch_size: 128

n_epochs: 450
init_lr: 0.05
weight_decay: 0.00005
opt_type: sgd

# net: proxyless_mobile

# net: mcunet-in1
# image_size: 96

# net: mcunet-in2
# image_size: 160

# net: mcunet-in3
# image_size: 176

net: mcunet-in4
image_size: 160

pretrained: false
origin_network: false
weight_quantization: false
weight_standardization: true
# choices=['proxyless_mobile', 'resnet', 'mcunet'])

transfer_learning_method: 'full'
# choices=[
#   'full', 'full_noBN', 'bn+last', 'last',
#   'tinytl-bias', 'tinytl-lite_residual', 'tinytl-lite_residual+bias'])