dataset: ImageNet
# choices=[
#     'aircraft', 'car', 'flowers102',
#     'food101', 'cub200', 'pets',
#     'cifar10', 'cifar100', 'ImageNet',])

n_epochs: 100
init_lr: 0.0003
label_smoothing: 0

# net: proxyless_mobile
net: mcunet-in2
# choices=['proxyless_mobile', 'resnet', 'mcunet'])

transfer_learning_method: 'last'
# choices=[
#   'full', 'full_noBN', 'bn+last', 'last',
#   'tinytl-bias', 'tinytl-lite_residual', 'tinytl-lite_residual+bias'])
origin_network: false

weight_quantization: false
frozen_param_bits: 8

weight_standardization: true