dataset: ImageNet
# choices=[
#     'aircraft', 'car', 'flowers102',
#     'food101', 'cub200', 'pets',
#     'cifar10', 'cifar100', 'ImageNet',])

n_epochs: 100
init_lr: 0.0003

net: proxyless_mobile
origin_network: false
weight_quantization: false
weight_standardization: true

# net: mcunet-in1
# origin_network: true
# weight_quantization: false
# weight_standardization: false
# fuse_bn_add_gn: true
# gn_channel_per_group: null

transfer_learning_method: 'last'
# choices=[
#   'full', 'full_noBN', 'bn+last', 'last',
#   'tinytl-bias', 'tinytl-lite_residual', 'tinytl-lite_residual+bias'])