dataset: ImageNet
# choices=[
#     'aircraft', 'car', 'flowers102',
#     'food101', 'cub200', 'pets',
#     'cifar10', 'cifar100', 'ImageNet',])

n_epochs: 100
init_lr: 0.0003

# net: proxyless_mobile
# origin_network: false
# weight_quantization: false
# weight_standardization: true

net: mcunet-in1
# pretrain_model_path: '/home/zyq123/Project/Edge/BackRazor_Neurips22/assets/mcunet_in1@ws+gn.pth.tar'
# net: mcunet-in4
# pretrain_model_path: '/home/zyq123/Project/Edge/BackRazor_Neurips22/assets/mcunet_in4@ws+gn.pth.tar'

###### origin_network: false -> replace BN with GN ######
origin_network: false
weight_standardization: true

###### origin_network: true, replace_norm_layer=null -> original network with BN ######
# origin_network: true
# replace_norm_layer: null
# weight_standardization: false

# fix_bn_stat: true

###### origin_network: true, replace_norm_layer choices=[null, 'fuse_bn', 'fuse_bn_add_gn', 'replace_bn_with_insn']) ######
# origin_network: true
# replace_norm_layer: fuse_bn
# weight_standardization: false

# origin_network: true
# replace_norm_layer: fuse_bn_add_gn
# gn_channel_per_group: 8
# weight_standardization: true

# origin_network: true
# replace_norm_layer: replace_bn_with_insn
# weight_standardization: false

weight_quantization: false

transfer_learning_method: 'last'
# choices=[
#   'full', 'full_noBN', 'bn+last', 'last',
#   'tinytl-bias', 'tinytl-lite_residual', 'tinytl-lite_residual+bias'])