# project: transfer
project: cifar10-cifar-10-c

##### dataset config #####
# choices=[
#     'aircraft', 'car', 'flowers102',
#     'food101', 'cub200', 'pets',
#     'cifar10', 'cifar100', 'ImageNet',
#     'cifar10-c', 'ImageNet-c'])

# dataset: car
# init_lr: 0.0003
# label_smoothing: 0.7

# dataset: cifar10
# init_lr: 0.00003
# label_smoothing: 0.1

# opt_type: adam
# train_batch_size: 8
# # train_batch_size: 1
# n_epochs: 100

dataset: cifar10-c
init_new_head: true
label_smoothing: 0
corruption_type: gaussian_noise
# corruption_type: [frost,gaussian_blur,gaussian_noise,glass_blur,impulse_noise,jpeg_compression,motion_blur,pixelate,saturate,shot_noise,snow,spatter,speckle_noise,zoom_blur]
severity: 5
train_n: 1000
# train_batch_size: 64
train_batch_size: 1
valid_size: 100
n_epochs: 20
init_lr: 0.00001
opt_type: sgd
# from CIFAR-10 pretrian
pretrain_model_path: '/home/zyq123/Project/Edge/BackRazor_Neurips22/exp/batch8/cifar10/mcunet-in1/last/20240721-184038-603275/checkpoint/model_best.pth.tar'
# pretrain_model_path: '/home/zyq123/Project/Edge/BackRazor_Neurips22/exp/batch8/cifar10/mcunet-in1/full/20240721-183737-600430/checkpoint/model_best.pth.tar'

# dataset: imagenet-c
# init_new_head: false
# label_smoothing: 0
# corruption_type: brightness
# # corruption_type: [brightness,contrast,defocus_blur,elastic_transform,fog,frost,gaussian_noise,glass_blur,impulse_noise,jpeg_compression,motion_blur,pixelate,shot_noise,snow,zoom_blur]
# severity: 5
# train_n: 5000
# # train_batch_size: 64
# train_batch_size: 1
# valid_size: 10000
# n_epochs: 10
# # init_lr: 0.001
# # opt_type: adam
# init_lr: 0.0001
# opt_type: sgd

##### RunConfig #####
validation_frequency: 1

##### Network config #####
# net: proxyless_mobile
# image_size: 224
# ### ws+gn
# # origin_network: false
# # weight_standardization: true

# ### bn
# origin_network: true
# weight_standardization: false
# # replace_norm_layer: fuse_bn

net: mcunet-in1
image_size: 128
# pretrain_model_path: '/home/zyq123/Project/Edge/BackRazor_Neurips22/assets/mcunet_in1@ws+gn.pth.tar'

# net: mcunet-in2
# image_size: 160

# net: mcunet-in4
# image_size: 160
# pretrain_model_path: '/home/zyq123/Project/Edge/BackRazor_Neurips22/assets/mcunet_in4@ws+gn.pth.tar'

###### origin_network: false -> replace BN with GN ######
# origin_network: false
# weight_standardization: true

###### origin_network: true, replace_norm_layer=null -> original network with BN/GN ######
# origin_network: true
# replace_norm_layer: null
# weight_standardization: false

# fix_bn_stat: true

###### origin_network: true, replace_norm_layer choices=[null, 'fuse_bn', 'fuse_bn_add_gn', 'replace_bn_with_insn']) ######
origin_network: true
replace_norm_layer: fuse_bn
weight_standardization: false

# origin_network: true
# replace_norm_layer: fuse_bn_add_gn
# gn_channel_per_group: 8
# weight_standardization: true

# origin_network: true
# replace_norm_layer: replace_bn_with_insn
# weight_standardization: false

##### Quantization config. default: true #####
weight_quantization: false

##### Transfer learning config #####

# transfer_learning_method: 'full'
# transfer_learning_method: 'full_noBN'
# transfer_learning_method: 'bn+last'
# transfer_learning_method: 'last'
# transfer_learning_method: 'bn_only'
transfer_learning_method: 'customize'   # train selected layers below only

train_first_conv: true

# trainable_blocks: [1,2]
# trainable_blocks: [1,2,3,4,5,6]
# trainable_blocks: [1,2,5,6]
trainable_blocks: [-2,-1]
# trainable_blocks: [-1,-4,-6,-7]
# trainable_blocks: [-1,-2,-4,-5,-6,-7]
# trainable_blocks: [-1,-2,-3,-4,-5,-6,-7,-8]

# trainable_layers: 'first'
# trainable_layers: 'no_dw'
trainable_layers: 'all'

# grad_output_prune_ratio: 0.8

##### Zeroth-Order config #####
ZO_Estim:
  ####### ZO_Estim_MC #######
  # en: True
  name: ZO_Estim_MC
  sigma: 0.01
  n_sample: 1
  signSGD: False

  # actv_perturb_layer_list: null
  actv_perturb_layer_list: ['inverted_bottleneck.conv',]
  # actv_perturb_layer_list: ['inverted_bottleneck.conv', 'point_linear.conv']
  # actv_perturb_block_idx_list: all
  actv_perturb_block_idx_list: [-2,]

  param_perturb_param_list: null
  # param_perturb_param_list: ['adapter_down.weight','adapter_up.weight']
  # param_perturb_block_idx_list: all
  # param_perturb_param_list: ['adapter_up.weight']
  # param_perturb_block_idx_list: [8,]

  # obj_fn_type: classifier
  obj_fn_type: classifier_layerwise

  quantized: False

  # estimate_method: forward
  estimate_method: antithetic

  # sample_method: uniform
  sample_method: gaussian
  # sample_method: bernoulli
  # sample_method: coord_basis

  normalize_perturbation: True
